/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getBootstrapOpsxSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-bootstrap-opsx',
    description: 'Bootstrap a draft openspec/project.opsx.yaml from existing specs and code. Use when the project has meaningful code/specs but no curated OPSX map yet.',
    instructions: `Bootstrap a draft \`openspec/project.opsx.yaml\` from the existing codebase and OpenSpec specs.

This is an **agent-driven** workflow. Do not add schema artifacts or runtime merge logic. Read the repository, infer the current capability graph, and write a human-reviewable draft.

**Input**: No argument required. If the user provides scope hints (domain names, folders, or capabilities), use them to focus the first pass.

**Steps**

1. **Check whether bootstrap is needed**
   - Look for \`openspec/openspec/project.opsx.yaml\`
   - If it already exists, ask whether to overwrite it, refresh it in place, or stop

2. **Collect project context**
   - Read \`package.json\`, \`README\`, and OpenSpec config files if present
   - Inspect \`openspec/specs/\` to discover domains and capabilities
   - Scan the codebase for implementation evidence and likely entrypoints

3. **Infer the OPSX graph**
   - Create a single project node from repository metadata
   - Group capabilities under inferred domains
   - Collect code references (file paths, line ranges) for a separate code-map file
   - Prefer a small, defensible graph over exhaustive noise

4. **Write the three OPSX files as a draft**
   - \`openspec/project.opsx.yaml\` — schema_version, project, domains, capabilities
   - \`openspec/project.opsx.relations.yaml\` — schema_version, relations
   - \`openspec/project.opsx.code-map.yaml\` — schema_version, generated_at, node code refs
   - Mark the files clearly as \`[DRAFT]\`
   - Include exactly three human review checkpoints:
     1. project/domain structure
     2. capability descriptions and boundaries
     3. code-map accuracy and coverage
   - Keep comments focused on why human review is needed
   - If information is missing, mark it as TBD instead of inventing detail

5. **Summarize the draft**
   - List the inferred domains
   - List the major capabilities per domain
   - Call out uncertain mappings that need review

**Drafting Guidelines**

- Start from \`openspec/specs/\` when available, then confirm against code
- Use repository evidence, not guesswork
- Keep naming stable and boring; avoid taxonomy churn
- Prefer fewer capabilities with solid code references over a bloated graph
- The output is a draft map of the current system, not a future design

**Output On Success**

\`\`\`
## OPSX Bootstrap Complete

Created: three OPSX files in \`openspec/\`

Status: [DRAFT]

Human review checkpoints:
1. Project/domain structure
2. Capability boundaries
3. Code-map coverage

Review the draft, then refine any uncertain domains or capability mappings.
\`\`\`

**Guardrails**
- Do NOT introduce runtime code for OPSX handling
- Do NOT fabricate code references
- Do NOT treat the draft as authoritative until a human reviews it
- Keep the first version small enough to audit in one sitting`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBootstrapCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bootstrap OPSX',
    description: 'Generate an initial draft openspec/project.opsx.yaml from existing specs and code',
    category: 'Workflow',
    tags: ['workflow', 'opsx', 'bootstrap', 'experimental'],
    content: `Bootstrap a draft \`openspec/project.opsx.yaml\` from the existing codebase and OpenSpec specs.

This is an **agent-driven** workflow. Do not add schema artifacts or runtime merge logic. Read the repository, infer the current capability graph, and write a human-reviewable draft.

**Input**: Optionally provide a scope hint after \`/opsx:bootstrap-opsx\` (domains, folders, or capabilities) to focus the first pass.

**Steps**

1. Check whether \`openspec/project.opsx.yaml\` already exists. If it does, ask whether to overwrite it, refresh it in place, or stop.
2. Read \`package.json\`, \`README\`, OpenSpec config files, and \`openspec/specs/\` for project/domain/capability context.
3. Scan the codebase for implementation evidence and derive code references.
4. Draft the three OPSX files:
   - \`openspec/project.opsx.yaml\` — schema_version, project, domains, capabilities
   - \`openspec/project.opsx.relations.yaml\` — schema_version, relations
   - \`openspec/project.opsx.code-map.yaml\` — schema_version, generated_at, node code refs
5. Mark the files as \`[DRAFT]\` and include exactly three human review checkpoints:
   1. project/domain structure
   2. capability descriptions and boundaries
   3. code-map accuracy and coverage
6. Summarize the draft and highlight uncertain mappings.

**Guardrails**
- Do NOT introduce runtime code for OPSX handling
- Do NOT fabricate code references
- Do NOT treat the draft as authoritative until a human reviews it
- Keep the first version small enough to audit in one sitting`
  };
}
