/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import { OPSX_NAVIGATION_GUIDANCE, OPSX_SHARED_CONTEXT } from '../fragments/opsx-fragments.js';

const IMPACT_SWEEP_GUIDANCE = `### Impact Sweeps

Invoke \`openspec-impact-sweeper\` when the user introduces a new module, workflow, command, configuration key, project concept, or unfamiliar domain term, or when preparing to say the discussion is ready for proposal/change artifacts.

Do not read \`openspec-impact-sweeper/SKILL.md\` in the main agent. \`openspec-impact-sweeper\` is a skill. Spawn a subagent and instruct it to read and execute the \`openspec-impact-sweeper\` skill, run the impact sweep with \`projectRoot\`, \`concept\`, optional \`optionalChangeName\`, optional \`knownUserTerms\`, and optional \`focus\`, and return only the JSON report path. Treat each new concept as an independent sweep, even if another concept was already swept earlier in the conversation. After the subagent returns the JSON report path, read that JSON report and interpret the findings in the explore conversation.

If the report contains terminology observations, decide before impact questions:
- If related specs use terms but none equals the user's term, ask: "你使用了'{userInput}'，相关 specs 中发现：\\n  - '{term1}'（{count1} 处，见 {specs1}）\\n是否指同一概念？"
- If specs use multiple terms and one equals the user's term, ask: "检测到术语不一致：\\n  - '{term1}'（{count1} 处）\\n  - '{term2}'（{count2} 处）\\n建议选择统一术语"
- If exactly one found term equals the user's term, or no related terms were found, continue silently.
- If the terminology field is missing, treat it as an old sweeper report and continue silently.

For terminology questions, show at most five terms and at most two spec names per term, appending "等" when truncated. Keep the question as natural Chinese and do not expose JSON keys, subagent names, or implementation terms.

When the user confirms the terms mean the same concept, record that term group in conversation state and continue the explore flow. When the user chooses a canonical term, record that canonical term and prefer it in later proposal/spec prose. When the user says the terms are different concepts, record the rejected term group. For any recorded same-concept, canonical-term, or rejected term group, do not ask again for that same group. These decisions guide later exploration and artifact drafting; they do not rewrite existing specs automatically.

If the report contains questions that affect scope or proposal readiness, ask the user instead of choosing silently. Do not claim proposal readiness until those scope-affecting questions are resolved or explicitly deferred by the user.`;

const BRAINSTORMING_GUIDANCE = `## Brainstorming Checklist

Explore MUST run this sequence before saying a proposal is ready:

1. **Explore project context**
   - Run \`openspec list --json\`.
   - Read relevant change artifacts when a change name is present.
   - Search or read relevant project files and git evidence when the idea maps to code.
   - If the request spans multiple independent subsystems, say so immediately, identify the subsystems, and recommend an implementation order.

2. **Visual companion when useful**
   - Use ASCII diagrams, flow charts, or comparison tables when the topic benefits from visual structure.
   - Skip this step for non-visual work such as backend APIs, data processing, CLI behavior, or narrow fixes.

3. **Clarify one question at a time**
   - Ask exactly one question, then wait for the answer.
   - Prefer a multiple-choice question when the choice set is clear.
   - Do not bundle unrelated questions.

4. **Compare 2-3 options**
   - Present 2-3 viable approaches.
   - For each option include description, strengths, weaknesses, and best fit.
   - Recommend one option and explain why.

5. **Confirm design in sections**
   - Present and confirm these sections one at a time: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
   - If the user asks for a change, revise that section and reconfirm it before continuing.

6. **Generate Design Summary**
   - Produce a \`Design Summary\` in the conversation, not in a file.
   - Include: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
   - End with: "设计总结已完成。请审查上述设计。如果确认无误，请调用 \`$openspec-propose <change-name>\` 生成制品。"`;

const ACTIVE_CHANGE_CAPTURE_GUIDANCE = `### Capture Boundary for Existing Changes

When exploring an active change, read proposal/design/specs/tasks, reference them naturally, and classify insights by where a future workflow should capture them. Do not update those artifacts in explore.

| Insight Type                         | Future Capture Target          |
|--------------------------------------|--------------------------------|
| Observable behavior requirement      | \`specs/<capability>/spec.md\` |
| Observable behavior changed          | \`specs/<capability>/spec.md\` |
| Refactor rationale or rejected path  | \`design.md\`                  |
| Implementation strategy              | \`design.md\`                  |
| Scope changed                        | \`proposal.md\`                |
| New work or verification identified  | \`tasks.md\`                   |
| OPSX graph intent changed            | \`opsx-delta.yaml\`            |
| Assumption invalidated               | Relevant artifact              |

Example offers:
- "That is a design decision for \`design.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."
- "This is observable behavior for \`specs/<capability>/spec.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."
- "This changes scope for \`proposal.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."`;

const EXPLORE_SUPPERPOWERS_STYLE_REFERENCE = `# Superpowers-Style Explore 行为引导

这份 reference 是 Superpowers brainstorming 在 OpenSpec explore 中的适配版。它恢复设计前置纪律，但不恢复原始 Superpowers 的文件写入、提交或实现计划权限。

## Superpowers brainstorming source

Superpowers brainstorming 的核心不是随意讨论，而是在实现前把模糊想法压成经用户确认的设计：
- 先读项目上下文，再判断问题边界。
- 一次只问一个澄清问题。
- 对关键选择给出 2-3 approaches、取舍和推荐。
- 分段展示设计，每段都等用户确认。
- 自检设计，交给用户 review。
- 通过明确交接进入下一工作流。

OpenSpec 的映射：
- 原始设计文档步骤映射为 conversation-only \`Design Summary\`。
- 原始提交步骤被移除；explore 不写文件。
- 原始实现计划交接映射为 \`openspec-propose\` handoff。

## Hard gate before implementation

Do not implement before design confirmation is complete.

Explore 期间不得开始编码、生成 patch、更新 artifacts，或把用户的方向确认解释成写入授权。即使用户说"可以"、"就这样"或选择某个方案，也只表示设计方向被确认。

Simple changes still require design confirmation. 小变更可以缩短设计，但不能跳过：至少确认问题、影响范围、方案和验证方式。

## Project context exploration

先用项目事实约束讨论：
- 读取相关 OpenSpec change、spec、design、tasks。
- 查看相关实现文件、测试和 git evidence。
- 识别受影响子系统；若请求横跨多个独立子系统，先拆清楚边界和推荐顺序。
- 明确未知项，不用一般经验替代项目证据。

## Just-in-time visual companion

视觉表达只在它能降低复杂度时使用。适合场景：
- 架构边界、状态机、数据流、依赖关系。
- 多方案对比。
- 用户卡在抽象关系上。

普通 CLI 行为、窄范围修复、字段命名、测试选择等问题，用简洁文本或表格即可；不要引入浏览器或 server companion。

## One-question discipline

每轮只问一个会改变设计的问题，问完等待用户回答。不要把 scope、API、数据模型、测试策略揉成一串问题。

如果选择集合清楚，优先给 2-3 个选项并说明差异；如果选择集合不清楚，先问能缩小问题空间的一个问题。

## 2-3 approaches

对关键设计点提供 2-3 approaches。每个方案包含：
- 方案描述。
- 优点。
- 缺点或风险。
- 最适合的场景。

给出推荐时必须说明原因，并把推荐绑定到项目约束，而不是偏好。

## Section-by-section design approval

按 section 推进设计，不一次性倾倒完整方案。常见 section：
- Architecture。
- Core components。
- Data flow。
- Technology stack。
- Testing strategy。
- Risks and trade-offs。

每个 section 结束时等待用户确认。用户要求修改时，只修正当前 section 并重新确认，然后再继续下一 section。

## Design Summary self-review

生成 \`Design Summary\` 前先自检：
- 是否仍有未解决的 scope 问题。
- 是否有占位符、含糊边界或互相矛盾的决策。
- 是否说明了测试策略和风险。
- 是否把文件写入、artifact 更新或后续生成动作留给非 explore workflow。

\`Design Summary\` 必须留在对话中，不创建或更新文件。内容聚焦架构、组件、数据流、技术栈、测试策略、风险和取舍。

## User review gate

向用户展示 \`Design Summary\` 后停止推进，让用户 review。用户要求改动时，回到对应 section 重新确认。

Only route to openspec-propose after the user reviews and accepts the Design Summary.

## openspec-propose handoff

用户确认 \`Design Summary\` 后，使用工具中立 workflow 名称交接：

\`\`\`
设计总结已完成。请审查上述设计。如果确认无误，请使用 openspec-propose 生成制品。
\`\`\`

不要在 reference 中使用工具特定调用语法。不要暗示 explore 可以创建 proposal、更新 design、修改 specs、提交文件或直接进入实现。`;

export function getExploreSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-explore',
    description: 'Enter explore mode - a thinking partner for exploring ideas, investigating problems, and clarifying requirements. Use when the user wants to think through something before or during a change.',
    referenceFiles: [
      {
        path: 'references/explore-supperpowers-style.md',
        content: EXPLORE_SUPPERPOWERS_STYLE_REFERENCE,
      },
    ],
    instructions: `Enter explore mode: investigate, clarify, compare, and help the user think before implementation.

## Required References

- Read \`openspec/references/openspec-explore-supperpowers-style.md\` before exploring. It is the authoritative Superpowers brainstorming behavior guide for hard gate, context exploration, visual companion judgment, one-question discipline, options comparison, section approval, Design Summary review, and propose handoff.
- Do not reconstruct or duplicate Superpowers behavior from this prompt. This prompt defines boundaries, context loading, sweeper delegation, and proposal routing only.

## Skill Delegation Protocol

**Internal Skills** — The following skill must NOT be invoked or read directly by this agent:
- \`openspec-impact-sweeper\` — it is a skill; delegate it to a subagent (see Impact Sweeps)

Do not read \`openspec-impact-sweeper/SKILL.md\` directly in the main agent.

## Hard Rules

- Explore is read-only for the main agent. Do not create, edit, delete, format, regenerate, or patch any project file or OpenSpec artifact.
- Only the subagent running the \`openspec-impact-sweeper\` skill may write its JSON report under \`openspec/sweeper/\`; the main explore agent may only read and interpret that report.
- The sweeper report write is an internal subagent exception and does not grant the main explore agent permission to create or modify project files or OpenSpec artifacts.
- User selection of an option, confirmation of a design section, or statements such as "可以", "就这样", "选 2", or "拆成多个文件" confirm design direction only. They are not authorization to modify files.
- Ask one clarification question at a time; do not auto-capture decisions into artifacts.
- When artifact generation is appropriate, produce a conversation-only \`Design Summary\` and instruct the user to call \`$openspec-propose <change-name>\`.

## Required Context

- Start with \`openspec list --json\`.
- Read relevant change artifacts when a change name is present.
- Use OPSX as navigation: project domains/capabilities, code-map refs, specs, and CLI query guidance.
- Ground claims in project files and git evidence when the idea maps to code.

${OPSX_SHARED_CONTEXT}

${OPSX_NAVIGATION_GUIDANCE}

## Mandatory Exploration Flow

1. Explore project context and identify affected subsystems.
2. Use a compact visual companion when it clarifies architecture, state, data flow, or trade-offs.
3. Ask exactly one scope/design question at a time.
4. Compare 2-3 viable options with strengths, weaknesses, best fit, and a recommendation when appropriate.
5. Confirm design sections one by one: architecture, components, data flow, tech stack, test strategy, risks/trade-offs.
6. Produce a conversation-only \`Design Summary\` and end with: "设计总结已完成。请审查上述设计。如果确认无误，请调用 \`$openspec-propose <change-name>\` 生成制品。"

## Impact Sweeps

Invoke \`openspec-impact-sweeper\` when the user introduces a new module, workflow, command, configuration key, project concept, or unfamiliar domain term, or when preparing to say the discussion is ready for proposal/change artifacts. Do not read \`openspec-impact-sweeper/SKILL.md\` in the main agent. \`openspec-impact-sweeper\` is a skill. Spawn a subagent and instruct it to read and execute the \`openspec-impact-sweeper\` skill, run the impact sweep with \`projectRoot\`, \`concept\`, optional \`optionalChangeName\`, optional \`knownUserTerms\`, and optional \`focus\`, and return only the JSON report path. Treat each new concept as an independent sweep, even if another concept was already swept earlier in the conversation. After the subagent returns the JSON report path, read that JSON report and interpret the findings in the explore conversation.

If the report contains terminology observations, decide before impact questions. When the user confirms the terms mean the same concept, record that term group and continue the explore flow. When the user chooses a canonical term, record that canonical term. When the user says the terms are different concepts, record the rejected term group. For any recorded same-concept, canonical-term, or rejected term group, do not ask again for that same group. Do not claim proposal readiness until those scope-affecting questions are resolved or explicitly deferred by the user.

## Brainstorming Checklist

Explore MUST run this sequence before saying a proposal is ready:
1. **Explore project context**. If the request spans multiple independent subsystems, identify them and recommend an implementation order.
2. **Visual companion when useful**.
3. **Clarify one question at a time**. Ask exactly one question, then wait for the answer.
4. **Compare 2-3 options**. Present 2-3 viable approaches.
5. **Confirm design in sections**: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
6. **Generate Design Summary**. Produce a \`Design Summary\` in the conversation, not in a file.

## Existing Changes

${ACTIVE_CHANGE_CAPTURE_GUIDANCE}`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
