/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import { OPSX_NAVIGATION_GUIDANCE, OPSX_SHARED_CONTEXT } from '../fragments/opsx-fragments.js';

const IMPACT_SWEEP_GUIDANCE = `### Impact Sweeps

Invoke \`openspec-impact-sweeper\` when the user introduces a new module, workflow, command, configuration key, project concept, or unfamiliar domain term, or when preparing to say the discussion is ready for proposal/change artifacts.

Do not read \`openspec-impact-sweeper/SKILL.md\` in the main agent. \`openspec-impact-sweeper\` is a skill. Spawn a subagent and instruct it to read and execute the \`openspec-impact-sweeper\` skill, run the impact sweep with \`projectRoot\`, \`concept\`, optional \`optionalChangeName\`, optional \`knownUserTerms\`, and optional \`focus\`, and return only the JSON report path. Treat each new concept as an independent sweep, even if another concept was already swept earlier in the conversation. After the subagent returns the JSON report path, read that JSON report and interpret the findings in the explore conversation.

If the report contains terminology observations, decide before impact questions:
- If related specs use terms but none equals the user's term, ask: "你使用了'{userInput}'，相关 specs 中发现：\\n  - '{term1}'（{count1} 处，见 {specs1}）\\n是否指同一概念？"
- If specs use multiple terms and one equals the user's term, ask: "检测到术语不一致：\\n  - '{term1}'（{count1} 处）\\n  - '{term2}'（{count2} 处）\\n建议选择统一术语"
- If exactly one found term equals the user's term, or no related terms were found, continue silently.
- If the terminology field is missing, treat it as an old sweeper report and continue silently.

For terminology questions, show at most five terms and at most two spec names per term, appending "等" when truncated. Keep the question as natural Chinese and do not expose JSON keys, subagent names, or implementation terms.

When the user confirms the terms mean the same concept, record that term group in conversation state and continue the explore flow. When the user chooses a canonical term, record that canonical term and prefer it in later proposal/spec prose. When the user says the terms are different concepts, record the rejected term group. For any recorded same-concept, canonical-term, or rejected term group, do not ask again for that same group. These decisions guide later exploration and artifact drafting; they do not rewrite existing specs automatically.

If the report contains questions that affect scope or proposal readiness, ask the user instead of choosing silently. Do not claim proposal readiness until those scope-affecting questions are resolved or explicitly deferred by the user.`;

const BRAINSTORMING_GUIDANCE = `## Brainstorming Checklist

Explore MUST run this sequence before saying a proposal is ready:

1. **Explore project context**
   - Run \`openspec list --json\`.
   - Read relevant change artifacts when a change name is present.
   - Search or read relevant project files and git evidence when the idea maps to code.
   - If the request spans multiple independent subsystems, say so immediately, identify the subsystems, and recommend an implementation order.

2. **Visual companion when useful**
   - Use ASCII diagrams, flow charts, or comparison tables when the topic benefits from visual structure.
   - Skip this step for non-visual work such as backend APIs, data processing, CLI behavior, or narrow fixes.

3. **Clarify one question at a time**
   - Ask exactly one question, then wait for the answer.
   - Prefer a multiple-choice question when the choice set is clear.
   - Do not bundle unrelated questions.

4. **Compare 2-3 options**
   - Present 2-3 viable approaches.
   - For each option include description, strengths, weaknesses, and best fit.
   - Recommend one option and explain why.

5. **Confirm design in sections**
   - Present and confirm these sections one at a time: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
   - If the user asks for a change, revise that section and reconfirm it before continuing.

6. **Generate Design Summary**
   - Produce a \`Design Summary\` in the conversation, not in a file.
   - Include: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
   - End with: "设计总结已完成。请审查上述设计。如果确认无误，请调用 \`$openspec-propose <change-name>\` 生成制品。"`;

const ACTIVE_CHANGE_CAPTURE_GUIDANCE = `### Capture Boundary for Existing Changes

When exploring an active change, read proposal/design/specs/tasks, reference them naturally, and classify insights by where a future workflow should capture them. Do not update those artifacts in explore.

| Insight Type                         | Future Capture Target          |
|--------------------------------------|--------------------------------|
| Observable behavior requirement      | \`specs/<capability>/spec.md\` |
| Observable behavior changed          | \`specs/<capability>/spec.md\` |
| Refactor rationale or rejected path  | \`design.md\`                  |
| Implementation strategy              | \`design.md\`                  |
| Scope changed                        | \`proposal.md\`                |
| New work or verification identified  | \`tasks.md\`                   |
| OPSX graph intent changed            | \`opsx-delta.yaml\`            |
| Assumption invalidated               | Relevant artifact              |

Example offers:
- "That is a design decision for \`design.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."
- "This is observable behavior for \`specs/<capability>/spec.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."
- "This changes scope for \`proposal.md\`; include it in the Design Summary, then call \`$openspec-propose <change-name>\` or the appropriate non-explore workflow."`;

const EXPLORE_STANCE_SECTION = `## The Stance

- **Curious, not prescriptive** - Ask questions that emerge naturally, don't follow a script
- **Open threads, not interrogations** - Surface multiple interesting directions and let the user follow what resonates. Don't funnel them through a single path of questions.
- **Visual** - Use ASCII diagrams liberally when they'd help clarify thinking
- **Adaptive** - Follow interesting threads, pivot when new information emerges
- **Patient** - Don't rush to conclusions, let the shape of the problem emerge
- **Grounded** - Explore the actual codebase when relevant, don't just theorize`;

const EXPLORE_WHAT_YOU_MIGHT_DO_SECTION = `## What You Might Do

Depending on what the user brings, you might:

**Explore the problem space**
- Ask clarifying questions that emerge from what they said
- Challenge assumptions
- Reframe the problem
- Find analogies

**Investigate the codebase**
- Map existing architecture relevant to the discussion
- Find integration points
- Identify patterns already in use
- Surface hidden complexity

**Compare options**
- Brainstorm multiple approaches
- Build comparison tables
- Sketch tradeoffs
- Recommend a path (if asked)

**Visualize**
\`\`\`
┌─────────────────────────────────────────┐
│     Use ASCII diagrams liberally        │
├─────────────────────────────────────────┤
│                                         │
│      ┌────────┐         ┌────────┐      │
│      │ State  │────────▶│ State  │      │
│      │   A    │         │   B    │      │
│      └────────┘         └────────┘      │
│                                         │
│   System diagrams, state machines,      │
│   data flows, architecture sketches,    │
│   dependency graphs, comparison tables  │
│                                         │
└─────────────────────────────────────────┘
\`\`\`

**Surface risks and unknowns**
- Identify what could go wrong
- Find gaps in understanding
- Suggest spikes or investigations`;

const EXPLORE_SUPPERPOWERS_STYLE_REFERENCE = `# Superpowers-Style Explore 行为引导

这份文档展开 explore 主 instructions 的行为清单，提供具体姿态说明、动作空间、入口点处理示例和收束模板。

---

${EXPLORE_STANCE_SECTION}

---

${EXPLORE_WHAT_YOU_MIGHT_DO_SECTION}

---

## Handling Different Entry Points

**User brings a vague idea:**
\`\`\`
User: I'm thinking about adding real-time collaboration

You: Real-time collab is a big space. Let me think about this...

      COLLABORATION SPECTRUM
      ════════════════════════════════════════════

      Awareness          Coordination         Sync
          │                   │                 │
          ▼                   ▼                 ▼
      ┌────────┐         ┌────────┐        ┌────────┐
      │Presence│         │Cursors │        │  CRDT  │
      │  "3    │         │ Multi  │        │Conflict│
      │online" │         │ select │        │  free  │
      └────────┘         └────────┘        └────────┘
          │                   │                 │
       trivial            moderate           complex

      Where's your head at?
\`\`\`

**User brings a specific problem:**
\`\`\`
User: The auth system is a mess

You: [reads codebase]

     ┌─────────────────────────────────────────────┐
     │              CURRENT AUTH FLOW              │
     └─────────────────────────────────────────────┘
                        │
          ┌─────────────┼─────────────┐
          ▼             ▼             ▼
     ┌─────────┐  ┌─────────┐  ┌─────────┐
     │ Google  │  │  GitHub │  │  Email  │
     │  OAuth  │  │  OAuth  │  │  Magic  │
     └────┬────┘  └────┬────┘  └────┬────┘
          │             │             │
          └─────────────┼─────────────┘
                        ▼
                  ┌───────────┐
                  │  Session  │
                  └─────┬─────┘
                        │
                        ▼
                  ┌───────────┐
                  │   Perms   │
                  └───────────┘

     I see three tangles. Which one's burning?
\`\`\`

**User is stuck mid-implementation:**
\`\`\`
User: Exploring add-auth-system
      The OAuth integration is more complex than expected

You: [reads change artifacts]

     You're on task 4: "Implement OAuth flow"

     Let me trace what's involved...

     [draws diagram, explores options, suggests paths]

     Call openspec-propose to update design.md with this insight.
\`\`\`

**User wants to compare options:**
\`\`\`
User: Should we use Postgres or SQLite?

You: Generic answer is boring. What's the context?

User: A CLI tool that tracks local dev environments

You: That changes everything.

     ┌─────────────────────────────────────────────────┐
     │          CLI TOOL DATA STORAGE                  │
     └─────────────────────────────────────────────────┘

     Key constraints:
     • No daemon running
     • Must work offline
     • Single user

                  SQLite          Postgres
     Deployment   embedded ✓      needs server ✗
     Offline      yes ✓           no ✗
     Single file  yes ✓           no ✗

     SQLite. Not even close.

     Unless... is there a sync component?
\`\`\`

---

## What We Figured Out

当探索结晶时，你可以提供总结模板（但这是可选的，有时思考本身就是价值）：

\`\`\`
## What We Figured Out

**The problem**: [crystallized understanding]

**The approach**: [if one emerged]

**Open questions**: [if any remain]

**Next steps** (if ready):
- Call openspec-propose to create artifacts from the Design Summary
- Keep exploring: just keep talking
\`\`\`

Discovery might:

- **Flow into a proposal**: "Ready to start? Call openspec-propose to create artifacts."
- **Just provide clarity**: User has what they need, moves on
- **Continue later**: "We can pick this up anytime"

Sometimes the thinking IS the value.`;

export function getExploreSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-explore',
    description: 'Enter explore mode - a thinking partner for exploring ideas, investigating problems, and clarifying requirements. Use when the user wants to think through something before or during a change.',
    referenceFiles: [
      {
        path: 'references/explore-supperpowers-style.md',
        content: EXPLORE_SUPPERPOWERS_STYLE_REFERENCE,
      },
    ],
    instructions: `Enter explore mode: investigate, clarify, compare, and help the user think before implementation.

## Required References

- Read \`openspec/references/openspec-explore-supperpowers-style.md\` before exploring. It is the authoritative Superpowers-style behavior guide for stance, action space, entry point handling, visualization examples, and closing templates.
- Do not reconstruct or duplicate Superpowers behavior from this prompt. This prompt defines boundaries, context loading, sweeper delegation, and proposal routing only.

## Skill Delegation Protocol

**Internal Skills** — The following skill must NOT be invoked or read directly by this agent:
- \`openspec-impact-sweeper\` — it is a skill; delegate it to a subagent (see Impact Sweeps)

Do not read \`openspec-impact-sweeper/SKILL.md\` directly in the main agent.

## Hard Rules

- Explore is read-only for the main agent. Do not create, edit, delete, format, regenerate, or patch any project file or OpenSpec artifact.
- Only the subagent running the \`openspec-impact-sweeper\` skill may write its JSON report under \`openspec/sweeper/\`; the main explore agent may only read and interpret that report.
- The sweeper report write is an internal subagent exception and does not grant the main explore agent permission to create or modify project files or OpenSpec artifacts.
- User selection of an option, confirmation of a design section, or statements such as "可以", "就这样", "选 2", or "拆成多个文件" confirm design direction only. They are not authorization to modify files.
- Ask one clarification question at a time; do not auto-capture decisions into artifacts.
- When artifact generation is appropriate, produce a conversation-only \`Design Summary\` and instruct the user to call \`$openspec-propose <change-name>\`.

## Required Context

- Start with \`openspec list --json\`.
- Read relevant change artifacts when a change name is present.
- Use OPSX as navigation: project domains/capabilities, code-map refs, specs, and CLI query guidance.
- Ground claims in project files and git evidence when the idea maps to code.

${OPSX_SHARED_CONTEXT}

${OPSX_NAVIGATION_GUIDANCE}

## Mandatory Exploration Flow

1. Explore project context and identify affected subsystems.
2. Use a compact visual companion when it clarifies architecture, state, data flow, or trade-offs.
3. Ask exactly one scope/design question at a time.
4. Compare 2-3 viable options with strengths, weaknesses, best fit, and a recommendation when appropriate.
5. Confirm design sections one by one: architecture, components, data flow, tech stack, test strategy, risks/trade-offs.
6. Produce a conversation-only \`Design Summary\` and end with: "设计总结已完成。请审查上述设计。如果确认无误，请调用 \`$openspec-propose <change-name>\` 生成制品。"

## Impact Sweeps

Invoke \`openspec-impact-sweeper\` when the user introduces a new module, workflow, command, configuration key, project concept, or unfamiliar domain term, or when preparing to say the discussion is ready for proposal/change artifacts. Do not read \`openspec-impact-sweeper/SKILL.md\` in the main agent. \`openspec-impact-sweeper\` is a skill. Spawn a subagent and instruct it to read and execute the \`openspec-impact-sweeper\` skill, run the impact sweep with \`projectRoot\`, \`concept\`, optional \`optionalChangeName\`, optional \`knownUserTerms\`, and optional \`focus\`, and return only the JSON report path. Treat each new concept as an independent sweep, even if another concept was already swept earlier in the conversation. After the subagent returns the JSON report path, read that JSON report and interpret the findings in the explore conversation.

If the report contains terminology observations, decide before impact questions. When the user confirms the terms mean the same concept, record that term group and continue the explore flow. When the user chooses a canonical term, record that canonical term. When the user says the terms are different concepts, record the rejected term group. For any recorded same-concept, canonical-term, or rejected term group, do not ask again for that same group. Do not claim proposal readiness until those scope-affecting questions are resolved or explicitly deferred by the user.

## Brainstorming Checklist

Explore MUST run this sequence before saying a proposal is ready:
1. **Explore project context**. If the request spans multiple independent subsystems, identify them and recommend an implementation order.
2. **Visual companion when useful**.
3. **Clarify one question at a time**. Ask exactly one question, then wait for the answer.
4. **Compare 2-3 options**. Present 2-3 viable approaches.
5. **Confirm design in sections**: architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs.
6. **Generate Design Summary**. Produce a \`Design Summary\` in the conversation, not in a file.

## Existing Changes

${ACTIVE_CHANGE_CAPTURE_GUIDANCE}`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
