/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-onboard',
    description: 'Guided onboarding for OpenSpec - walk through a complete workflow cycle with narration and real codebase work.',
    instructions: getOnboardInstructions(),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function getOnboardInstructions(): string {
  return `Guide the user through one real OpenSpec workflow cycle while teaching by doing.

## Protocol

1. Preflight: run \`openspec --version\`; stop with install guidance if unavailable.
2. Welcome: explain the cycle briefly: choose task -> explore -> create change -> proposal/specs/design/tasks -> apply -> archive.
3. Select a small real task by scanning for TODO/FIXME, missing tests, weak validation, swallowed errors, debug artifacts, or simple type issues. Also inspect recent git history. Present 3-4 concrete options with file paths and small scope estimates. If the chosen task is large, suggest a smaller slice but let the user override.
4. Explore demo: read the relevant files, summarize what matters, and optionally draw a compact ASCII diagram. Pause for acknowledgment.
5. Create the change with \`openspec new change "<derived-name>"\`.
6. Build artifacts in order. For each artifact, run \`openspec instructions <artifact-id> --change "<name>" --json\`, follow the returned template/instruction/outputPath exactly, read dependency artifacts first, and preserve canonical headings, BDD keywords, IDs, paths, commands, and code identifiers. Apply \`openspec/config.yaml\` only through the compiled prompt projection.
7. Pause after proposal draft and before implementation so the user can correct the teaching example.
8. Apply implementation tasks one at a time. Announce the task, implement the minimal code, mark the checkbox complete only after evidence passes, and keep narration light.
9. Archive with \`openspec archive "<name>"\` after tasks are complete and verification gates pass.
10. Recap the cycle and point to the created change/archive location.

## Guardrails

- Use real codebase work; do not simulate examples.
- Keep every teaching explanation short and tied to the current file or artifact.
- Do not skip phases during onboarding; the point is learning the whole loop.
- If the user pauses, say where the change is saved and how to resume with \`/opsx:continue <name>\` or \`/opsx:apply <name>\`.
- If the user only wants a reference, show the core commands: \`/opsx:explore\`, \`/opsx:propose\`, \`/opsx:apply\`, \`/opsx:verify\`, \`/opsx:archive\`.`;
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: 'Guided onboarding - walk through a complete OpenSpec workflow cycle with narration',
    category: 'Workflow',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: getOnboardInstructions(),
  };
}
