/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import {
  CLEAN_CONTEXT_VERIFY_PROTOCOL_REREAD,
  CONFORMANCE_CHECK_RULES,
  GIT_EVIDENCE_PROTOCOL,
  OPTIMIZATION_PROTOCOL_SUBAGENT,
  OPSX_VERIFY_ALIGNMENT,
  VERIFY_WRITEBACK_RULES,
} from '../fragments/opsx-fragments.js';

interface VerifyTemplateText {
  input: string;
  commandPrefix?: string;
}

function buildVerifyInstructions(
  text: VerifyTemplateText,
  cleanContextProtocol: string
): string {
  const verifyInvocation = `${text.commandPrefix ?? '/opsx:'}verify`;
  const continueInvocation = `${text.commandPrefix ?? '/opsx:'}continue`;

  return `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: ${text.input}

When verification writes remediation guidance or instructs artifact updates, treat \`openspec/config.yaml\` as the compact source of truth and follow the shared prompt/runtime projection contract. Preserve \`tasks.md\` structure tokens, checkboxes, requirement references, and canonical section headings.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

1.5. **Clean-Context Verification Setup**

${cleanContextProtocol}

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. **Get the change directory and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If \`tasks.md\` exists in \`contextFiles\`, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add one CRITICAL issue per incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`openspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search for candidate implementation files
       - Read the final file contents for those candidates
       - Assess whether credible implementation evidence exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

5.5. **Git Evidence Investigation**

${GIT_EVIDENCE_PROTOCOL}

   Use git commands to guide the investigation:
   - Run \`git status\` to find modified, added, and deleted files
   - Run \`git diff\` to identify candidate implementation areas and suspicious omissions
   - Run \`git log -5 --oneline\` to understand recent context if needed

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search for implementation evidence in code and tests
     - Read final file contents before assigning status
     - Record supporting and contradicting evidence with specific file paths and line ranges
     - If divergence is detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check whether the scenario conditions are handled in code
     - Check whether tests cover the scenario
     - If scenario coverage is incomplete or unclear:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

${CONFORMANCE_CHECK_RULES}

${OPSX_VERIFY_ALIGNMENT}

7. **Verify Coherence**

   **Design Adherence**:
   - If \`design.md\` exists in \`contextFiles\`:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction is detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no \`design.md\` exists: skip design adherence and state why

   **Code Pattern Consistency**:
   - Review new code for consistency with existing project patterns
   - Check naming, directory structure, and testing shape
   - If significant deviation is found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status                |
   |--------------|-----------------------|
   | Completeness | X/Y tasks, N reqs     |
   | Correctness  | M/N reqs covered      |
   | Coherence    | Followed/Issues       |
   | Optimization | SKIPPED / IMPROVED... |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (must fix before archive)
   2. **WARNING** (should fix or consciously accept)
   3. **SUGGESTION** (non-blocking improvements)

   **Final Assessment**:
   - If CRITICAL issues exist: set result to \`FAIL_NEEDS_REMEDIATION\`
   - If no CRITICAL issues exist but warnings or suggestions remain: set result to \`PASS_WITH_WARNINGS\`
   - If all checks are clear: set result to \`PASS\`

   **Exit / Result Semantics**:
   - \`PASS\`: no CRITICAL, WARNING, or SUGGESTION follow-up is needed
   - \`PASS_WITH_WARNINGS\`: no CRITICAL issues, but warnings or suggestions remain
   - \`FAIL_NEEDS_REMEDIATION\`: one or more CRITICAL issues require write-back and rework

9. **Write Back CRITICAL Issues**

${VERIFY_WRITEBACK_RULES}

   - If no CRITICAL issues were found, leave \`tasks.md\` unchanged
   - If CRITICAL issues were found:
     - Unmark each affected completed task
     - Append or refresh the \`## Remediation\` section with typed fix items
     - Include the requirement name, issue summary, and owning task when possible

10. **Prepare the Canonical Phase 1 Result**

   - Assemble the canonical Phase 1 payload before any optimization attempt
   - Record:
     - \`timestamp\`: ISO 8601 completion time
     - \`result\`: \`PASS\` / \`PASS_WITH_WARNINGS\` / \`FAIL_NEEDS_REMEDIATION\`
     - \`issues\`: the full issue list with severity, requirement, task linkage, and recommendations
     - \`tasksFileHash\`: hash of the current \`tasks.md\` contents after any write-back
     - \`verificationContext\`:
       - \`contractVersion\`: \`"1.0"\`
       - \`executionMode\`: derived from Step 1.5
       - \`evidenceFiles\`: sorted list of examined files using relative POSIX paths
       - \`evidenceFingerprint\`: SHA-256 of sorted evidence file path + modification time + size tuples
       - \`gitHeadCommit\`: current HEAD commit SHA if available
       - \`gitDiffSummary\`: output of \`git diff --stat\` if useful
   - Compute \`evidenceFingerprint\` by sorting \`evidenceFiles\`, collecting each file's normalized relative path, mtime, and size, then hashing the concatenated string
   - Use \`path.join()\`, \`path.resolve()\`, and \`path.normalize()\` for all path handling
   - Treat this payload as the immutable \`optimization.baseline\`

11. **Run Phase 2 Optimality Check**

   - Phase 2 is only eligible when the canonical Phase 1 \`result\` is \`PASS\` or \`PASS_WITH_WARNINGS\`
   - Read \`optimization.enabled\` from \`openspec/config.yaml\`; default it to \`true\` when the field is absent
   - Respect a user-provided \`--skip-optimization\` flag if the workflow surface supports flags
   - If the user passed \`--skip-optimization\` or config disables optimization:
     - Skip Phase 2
     - Set \`optimization.status\` to \`SKIPPED\`
     - Keep the canonical Phase 1 \`result\` unchanged
   - Otherwise create a checkpoint with \`git stash push -u -m "verify-phase2-checkpoint"\`
   - Record the exact stash entry or hash before applying any optimization edits
   - Immediately restore the canonical Phase 1 baseline into the worktree while keeping the checkpoint available, for example with \`git stash apply <checkpointRef>\`
   - If checkpoint creation or baseline restoration fails:
     - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
     - Report that the canonical Phase 1 result was preserved but checkpoint recovery is required
     - Stop before applying any optimization edits

${OPTIMIZATION_PROTOCOL_SUBAGENT}

   **Main-agent application contract**:
   - Parse every Search/Replace block before touching the filesystem
   - Resolve target paths with \`path.join()\`, \`path.resolve()\`, and \`path.normalize()\`
   - Use \`path.join()\` for any checkpoint-adjacent bookkeeping paths; never hardcode path separators
   - Reject blocks that create, delete, rename, or target untracked files
   - Pre-validate all blocks, then apply them atomically
   - If the subagent returns \`No optimization opportunities found\`, set \`optimization.status\` to \`NOT_NEEDED\` and keep the canonical Phase 1 \`result\`

12. **Re-verify Candidate Changes and Enforce Retry Budgets**

   - Re-run the same verification contract in \`P1_SPECULATIVE_FENCE\` mode after applying candidate Search/Replace blocks
   - \`P1_SPECULATIVE_FENCE\` MUST reuse the same completeness/correctness/coherence checks but MUST NOT:
     - write back to \`tasks.md\`
     - rewrite the canonical \`.verify-result.json\`
   - On speculative \`PASS\` or \`PASS_WITH_WARNINGS\`:
     - Finalize the optimized files
     - Drop the checkpoint with \`git stash drop\`
     - Set \`optimization.status\` to \`IMPROVED\`
   - On speculative \`FAIL_NEEDS_REMEDIATION\`:
     - Discard speculative edits completely
     - Restore the exact canonical Phase 1 baseline from the checkpoint, for example with \`git reset --hard HEAD\`, \`git clean -fd\`, then \`git stash apply <checkpointRef>\`
     - Increment the behavior retry counter
     - Request a materially different optimization strategy
   - Retry budgets are fixed:
     - \`maxFormatRetries = 2\`
     - \`maxMatchRetries = 2\`
     - \`maxBehaviorFailures = 3\`
   - Count format errors separately from behavioral regressions:
     - malformed Search/Replace blocks consume format retries
     - zero-match or multi-match SEARCH anchors consume match retries
     - speculative re-verify failures consume behavior retries
   - If the format or match budget is exhausted:
     - Restore the exact canonical Phase 1 baseline from the checkpoint if any speculative edits were applied
     - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
     - Keep the canonical Phase 1 \`result\`
   - If behavior failures reach 3:
     - Restore the exact canonical Phase 1 baseline from the checkpoint
     - Report: \`Phase 1 PASS. 3 optimization attempts safely reverted.\`
     - Set \`optimization.status\` to \`DEGRADED\`
     - Set top-level \`result\` to \`PASS_WITH_WARNINGS\`
   - If the optimization subagent times out or internal safety is uncertain:
     - Restore the exact canonical Phase 1 baseline from the checkpoint if any speculative edits were applied
     - Report: \`Optimization phase aborted, but canonical verification passed.\`
     - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
     - Keep the canonical Phase 1 \`result\`

13. **Persist Final Verification Result**

   - Build the verify result path with \`path.join(changeDir, '.verify-result.json')\`
   - Write the final JSON object after Phase 2 completes or is skipped
   - Persist:
     - the canonical Phase 1 payload
     - the final top-level \`result\`
     - an \`optimization\` object containing:
       - \`status\`: \`SKIPPED\` / \`NOT_NEEDED\` / \`IMPROVED\` / \`DEGRADED\` / \`ABORTED_UNSAFE\`
       - \`score\`: optional optimization assessment summary when the tool can justify one
       - \`attempts\`: an ordered log of format, match, and behavior retries
       - \`baseline\`: reference to the canonical Phase 1 payload
       - \`final\`: the accepted optimized outcome or the safe rollback outcome
   - Persist the file even when verification fails so \`${verifyInvocation}\`, \`${continueInvocation}\`, and archive can consume the latest diagnostics

**Verification Heuristics**

- **Completeness**: focus on objective checklist items and explicit requirement coverage
- **Correctness**: require concrete evidence from final file contents before declaring PASS
- **Coherence**: look for meaningful contradictions, not cosmetic nitpicks
- **Optimization**: improve code only when behavior can be preserved under checkpoint protection
- **False positives**: when uncertain, prefer SUGGESTION over WARNING and WARNING over CRITICAL
- **Actionability**: every issue must include a concrete next action and file references when applicable

**Graceful Degradation**

- If only \`tasks.md\` exists: verify task completion only and report skipped checks
- If tasks and specs exist: verify completeness and correctness, skip design checks
- If full artifacts exist: verify all three dimensions
- Always state which checks were skipped and why

**Output Format**

Use clear markdown with:
- A table for the summary scorecard
- Grouped lists for CRITICAL, WARNING, and SUGGESTION issues
- Code references in \`file.ts:123\` format
- Specific, actionable recommendations
- No vague language like "consider reviewing"`;
}

function createVerifySkillTemplate(cleanContextProtocol: string): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description:
      'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: buildVerifyInstructions(
      {
        input:
          'Optionally specify a change name and optionally request `--skip-optimization`. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.',
      },
      cleanContextProtocol
    ),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function createVerifyCommandTemplate(cleanContextProtocol: string): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: buildVerifyInstructions(
      {
        input:
          'Optionally specify a change name after `/opsx:verify` (e.g., `/opsx:verify add-auth`) and optionally pass `--skip-optimization`. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.',
      },
      cleanContextProtocol
    ),
  };
}

export function createVerifyChangeSkillTemplate(
  cleanContextProtocol: string = CLEAN_CONTEXT_VERIFY_PROTOCOL_REREAD
): SkillTemplate {
  return createVerifySkillTemplate(cleanContextProtocol);
}

export function createOpsxVerifyCommandTemplate(
  cleanContextProtocol: string = CLEAN_CONTEXT_VERIFY_PROTOCOL_REREAD
): CommandTemplate {
  return createVerifyCommandTemplate(cleanContextProtocol);
}

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return createVerifyChangeSkillTemplate();
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return createOpsxVerifyCommandTemplate();
}
