/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import {
  CLEAN_CONTEXT_VERIFY_PROTOCOL_SUBAGENT,
  CLEAN_CONTEXT_VERIFY_PROTOCOL_REREAD,
  CONFORMANCE_CHECK_RULES,
  GIT_EVIDENCE_PROTOCOL,
  OPSX_VERIFY_ALIGNMENT,
  VERIFY_COORDINATOR_ROLE,
  VERIFY_CLI_JSON_SCHEMA_REFERENCE,
  VERIFY_ERROR_RECOVERY_GUIDE,
  VERIFY_SIMPLE_CHANGE_FAST_PATH,
  VERIFY_STATE_MACHINE_DIAGRAM,
  VERIFY_SUBAGENT_TIMEOUT_RULES,
  VERIFY_WRITEBACK_RULES,
} from '../fragments/opsx-fragments.js';
import {
  REREAD_VERIFY_EXECUTION_MODEL,
  SUBAGENT_VERIFY_EXECUTION_MODEL,
  type VerifyExecutionModel,
} from './verify-execution-model.js';

interface VerifyTemplateText {
  input: string;
  commandPrefix?: string;
}

function buildVerifyIntro(text: VerifyTemplateText, cleanContextProtocol: string): string {
  const continueInvocation = `${text.commandPrefix ?? '/opsx:'}continue`;

  return `${VERIFY_COORDINATOR_ROLE}

**Mode Label Reference**:

| Mode Label | Phase | Trigger |
| --- | --- | --- |
| \`[Mode: Setup]\` | Select change, load artifacts, and run early-stop checks | Steps 1-3.5 |
| \`[Mode: Evidence]\` | Gather git evidence and final file contents | Step 4 |
| \`[Mode: Delegate Review]\` | Start reviewer subagent and wait for structured payload | Step 5 |
| \`[Mode: Validate Payload]\` | Validate reviewer payload structure and evidence references | Step 6 |
| \`[Mode: Writeback]\` | Apply writeBackPlan to \`tasks.md\` | Step 7/9 |
| \`[Mode: Record]\` | Persist canonical Phase 1 result through CLI | Step 8/10 |
| \`[Mode: Checkpoint]\` | Manage Phase 2 git checkpoint lifecycle | Phase 2 entry |
| \`[Mode: Optimize]\` | Start optimizer subagent and apply Search/Replace blocks | Phase 2 optimization |
| \`[Mode: Speculative Verify]\` | Re-verify candidate changes without touching canonical result | Step 10/12 |
| \`[Mode: Seal]\` | Run final seal validation | Step 11/13 |

Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: ${text.input}

When verification writes remediation guidance or instructs artifact updates, treat \`openspec/config.yaml\` as the compact source of truth and follow the shared prompt/runtime projection contract. Preserve \`tasks.md\` structure tokens, checkboxes, requirement references, and canonical section headings.

**Steps**

1. [Mode: Setup] **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Ask the user to select a change.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

1.5. [Mode: Setup] **Clean-Context Verification Setup**

${cleanContextProtocol}

2. [Mode: Setup] **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. [Mode: Setup] **Get the change directory and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

3.5. [Mode: Setup] **Stop early if no verifyable tasks exist**

   - If \`tasks.md\` is missing from \`contextFiles\`, unreadable, or contains no checkbox tasks:
     - Report exactly: "没有可供 verify 的任务"
     - Recommend running \`${continueInvocation}\` to create tasks
     - Stop the workflow before any completeness / correctness / coherence judgment
     - Do NOT write \`.verify-result.json\`
`;
}

function buildCanonicalPhase1Step(stepNumber: number): string {
  return `${stepNumber}. [Mode: Record] **Persist the Canonical Phase 1 Result Through CLI**

   - Assemble the canonical Phase 1 payload before any optimization attempt, then submit it through:
     \`\`\`bash
     openspec verify phase1 "<change-name>" --input '<json>' --json
     \`\`\`
   - The CLI records:
     - \`timestamp\`: ISO 8601 completion time
     - \`result\`: \`PASS\` / \`PASS_WITH_WARNINGS\` / \`FAIL_NEEDS_REMEDIATION\`
     - \`issues\`: the full issue list with severity, requirement, task linkage, and recommendations
     - \`tasksFileHash\`: hash of the current \`tasks.md\` contents after any write-back
     - \`verificationContext\`:
       - \`contractVersion\`: \`"1.0"\`
       - \`executionMode\`: derived from Step 1.5
       - \`evidenceFiles\`: sorted list of examined files using relative POSIX paths
       - \`evidenceFingerprint\`: SHA-256 of sorted relative POSIX path + content hash entries
       - \`gitHeadCommit\`: current HEAD commit SHA if available
       - \`gitDiffSummary\`: output of \`git diff --stat\` if useful
${VERIFY_CLI_JSON_SCHEMA_REFERENCE}
   - Provide \`evidenceFiles\` as relative POSIX paths; the CLI computes \`tasksFileHash\` and \`evidenceFingerprint\` with \`path.join()\`, \`path.resolve()\`, and \`path.normalize()\`
   - Treat the persisted CLI payload as the immutable \`optimization.baseline\``;
}

function buildPhase2Step(stepNumber: number): string {
  return `${stepNumber}. [Mode: Checkpoint] **Submit Phase 2 Optimization Through CLI**

   - Phase 2 is only eligible when the canonical Phase 1 \`result\` is \`PASS\` or \`PASS_WITH_WARNINGS\`
   - Read \`optimization.enabled\` from \`openspec/config.yaml\`; default it to \`true\` when the field is absent
   - Read \`optimization.optRetries\` from \`openspec/config.yaml\`; default it to \`2\` when the field is absent
   - Respect a user-provided \`--skip-optimization\` flag if the workflow surface supports flags
   - If the user passed \`--skip-optimization\` or config disables optimization:
     - Call \`openspec verify phase2 "<change-name>" --type=optimization --input '{"status":"SKIPPED"}' --json\`
     - Keep the canonical Phase 1 \`result\` unchanged
   - For pure deletions, renames, or parameter removals with no meaningful optimization room, use the simple-change fast path and skip the optimization subagent
${VERIFY_SIMPLE_CHANGE_FAST_PATH}
${VERIFY_STATE_MACHINE_DIAGRAM}

   - Otherwise run an explicit checkpoint state machine:

     | State | Trigger condition | Git operation |
     | --- | --- | --- |
     | \`CREATED\` | Before applying any optimization edits | \`git stash push -u -m "verify-phase2-checkpoint"\`; record the exact stash entry or hash |
     | \`BASELINE_RESTORED_FOR_RETRY\` | Retry after speculative reverify failure | \`git stash apply <checkpointRef>\`; restore the canonical Phase 1 baseline while preserving the checkpoint |
     | \`TERMINAL_ACCEPTED\` | Optimized result is accepted | \`git stash drop <checkpointRef>\`; consume the checkpoint after acceptance |
     | \`TERMINAL_RESTORED\` | Final rollback succeeds | \`git stash pop <checkpointRef>\` or equivalent restore-then-drop sequence; restore baseline and consume the checkpoint |

   Hard rules:
   - Record the exact stash entry or hash before applying any optimization edits
   - Immediately restore the canonical Phase 1 baseline into the worktree while keeping the checkpoint available, for example with \`git stash apply <checkpointRef>\`
   - If checkpoint creation or baseline restoration fails:
     - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
     - Preserve the stash entry whenever manual recovery still depends on it
     - Report that the canonical Phase 1 result was preserved but checkpoint recovery is required
     - Stop before applying any optimization edits
   - Treat \`git stash apply <checkpointRef>\` as the retry-only restore path
   - Treat \`git stash pop <checkpointRef>\` as the preferred terminal restore path once no further retries are allowed
   - Any branch that still outputs manual recovery instructions MUST NOT run \`git stash drop <checkpointRef>\` first
${VERIFY_ERROR_RECOVERY_GUIDE}

**[Mode: Optimize] Phase 2 Optimization Protocol**:

   Delegate to a clean-context optimizer subagent. The coordinator MUST pass the optimization
   input contract below and instruct the subagent to invoke the \`openspec-optimizer\` skill.

   The \`openspec-optimizer\` skill defines: role and hard constraints, input contract,
   prioritized optimization principles (5 categories + prohibition list), Search/Replace block
   output format, and failed directions avoidance protocol.

   **Inputs to pass to the optimizer subagent**:
   - Canonical Phase 1 summary, issues, and evidence file list
   - Change artifacts: proposal.md, specs/, design.md, tasks.md
   - Final file contents for the candidate implementation files
   - Project policy context from openspec/config.yaml, including optimization.enabled
   - failedDirections from prior optimization attempts (if any)

   The optimizer subagent MUST return only Search/Replace blocks or exactly
   \`No optimization opportunities found\`; it MUST NOT edit files directly.
   The coordinator MUST wait for the complete optimizer payload before applying blocks
   or recording NO_OPTIMIZATION_NEEDED.

${VERIFY_SUBAGENT_TIMEOUT_RULES}

   If the subagent returns \`No optimization opportunities found\`, record NO_OPTIMIZATION_NEEDED.
   Otherwise, apply the returned Search/Replace blocks atomically, then delegate to the reviewer subagent
   for speculative re-verification.

   **Main-agent application contract**:
   - Parse every Search/Replace block before touching the filesystem
   - Resolve target paths with \`path.join()\`, \`path.resolve()\`, and \`path.normalize()\`
   - Use \`path.join()\` for any checkpoint-adjacent bookkeeping paths; never hardcode path separators
   - Reject blocks that create, delete, rename, or target untracked files
   - Pre-validate all blocks, then apply them atomically
   - If the subagent returns \`No optimization opportunities found\`, call:
     \`\`\`bash
     openspec verify phase2 "<change-name>" --type=optimization --input '{"status":"NO_OPTIMIZATION_NEEDED"}' --json
     \`\`\`
     The CLI records terminal \`optimization.status = NOT_NEEDED\`
   - If an optimization is proposed and applied to files, call:
     \`\`\`bash
     openspec verify phase2 "<change-name>" --type=optimization --files "path/to/file.ts" --input '{"status":"OPTIMIZATION_PROPOSED","summary":"..."}' --json
     \`\`\`
   - The CLI stores \`optimization.status = PENDING_VERIFICATION\`, appends \`optimization.attempts\`, and records \`optimization.affectedFileHashes\`
${VERIFY_CLI_JSON_SCHEMA_REFERENCE}
`;
}

function buildReverifyStep(stepNumber: number, speculativeFenceContract: string): string {
  return `${stepNumber}. [Mode: Speculative Verify] **Re-verify Candidate Changes and Enforce Retry Budgets**

   - Re-run the same verification contract in \`P1_SPECULATIVE_FENCE\` mode after applying candidate Search/Replace blocks
${speculativeFenceContract}
   - For subagent-orchestrated speculative verification, delegate to a clean-context reviewer subagent, instruct it to invoke the \`openspec-reviewer\` skill, and pass:
     - Change artifacts from the speculative worktree
     - Git evidence for the speculative worktree
     - Final file contents for every changed candidate file
     - Canonical Phase 1 result and optimization attempt summary
     - Prior \`.verify-result.json\` when present
   - Wait for the complete reviewer payload before deciding whether the optimization passed or failed
${VERIFY_SUBAGENT_TIMEOUT_RULES}
   - \`P1_SPECULATIVE_FENCE\` MUST reuse the same completeness/correctness/coherence checks but MUST NOT:
     - write back to \`tasks.md\`
     - rewrite the canonical \`.verify-result.json\`
   - On speculative \`PASS\` or \`PASS_WITH_WARNINGS\`:
     - Finalize the optimized files
     - Consume the checkpoint with \`git stash drop <checkpointRef>\` only after the optimized result is accepted
     - Transition the checkpoint state to \`TERMINAL_ACCEPTED\`
     - Call \`openspec verify phase2 "<change-name>" --type=verification --input '{"result":"PASS","issues":[]}' --json\` so the CLI sets \`optimization.status\` to \`IMPROVED\`
   - On speculative \`FAIL_NEEDS_REMEDIATION\`:
     - Discard speculative edits completely
     - Restore the exact canonical Phase 1 baseline from the checkpoint, for example with \`git reset --hard HEAD\`, \`git clean -fd\`, then \`git stash apply <checkpointRef>\`
     - Keep the checkpoint for the next retry and transition back to \`BASELINE_RESTORED_FOR_RETRY\`
     - Increment the behavior retry counter
     - Request a materially different optimization strategy
     - Call \`openspec verify phase2 "<change-name>" --type=verification --input '{"result":"FAIL_NEEDS_REMEDIATION","issues":[...],"behaviorRetryCounter":N}' --json\` before retrying optimization
   - \`config.optimization.optRetries\` is the only retry budget for complete proposal + patch + re-verify cycles
   - Format and match problems stay in the main agent:
     - malformed Search/Replace blocks must be fixed before any file write
     - zero-match or multi-match SEARCH anchors must be repaired before speculative verification
     - these local repairs do not consume \`optRetries\`
   - If a format or match defect cannot be repaired safely:
     - Restore the exact canonical Phase 1 baseline from the checkpoint if any speculative edits were applied
     - Finish the workflow with a terminal restore: prefer \`git stash pop <checkpointRef>\`, or use an equivalent restore-success-then-drop sequence
     - If terminal restore succeeds:
       - Transition the checkpoint state to \`TERMINAL_RESTORED\`
       - Resolve the run as a warning-only, non-\`ABORTED_UNSAFE\` terminal outcome because the baseline was safely restored
       - Keep the canonical Phase 1 \`result\` or widen it to \`PASS_WITH_WARNINGS\` only when the final report needs to disclose degraded optimization coverage
     - If terminal restore fails:
       - Preserve the stash entry for manual recovery
       - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
       - Output cross-platform recovery instructions using \`git reset --hard HEAD\`, \`git clean -fd\`, and \`git stash apply <checkpointRef>\`
   - If behavior failures reach \`config.optimization.optRetries\`:
     - Discard speculative edits and restore the exact canonical Phase 1 baseline from the checkpoint
     - Consume the checkpoint only after baseline restoration succeeds, preferably with \`git stash pop <checkpointRef>\`
     - Transition the checkpoint state to \`TERMINAL_RESTORED\`
     - Report: \`Phase 1 PASS. N optimization attempts safely reverted.\`
     - Set \`optimization.status\` to \`DEGRADED\`
     - Set top-level \`result\` to \`PASS_WITH_WARNINGS\`
   - If the optimization subagent times out or internal safety is uncertain:
     - Restore the exact canonical Phase 1 baseline from the checkpoint if any speculative edits were applied
     - Attempt terminal recovery without consuming the checkpoint until restore success is confirmed
     - If recovery succeeds:
       - Transition the checkpoint state to \`TERMINAL_RESTORED\`
       - Report a warning-only outcome because optimization stopped early but the canonical baseline was safely restored
       - Keep the canonical Phase 1 \`result\` or widen it to \`PASS_WITH_WARNINGS\` if the final report needs to disclose degraded optimization coverage
     - If recovery fails:
       - Preserve the stash entry for manual recovery
       - Set \`optimization.status\` to \`ABORTED_UNSAFE\`
       - Keep the canonical Phase 1 \`result\`
`;
}

function buildPersistStep(
  stepNumber: number,
  verifyInvocation: string,
  continueInvocation: string
): string {
  return `${stepNumber}. [Mode: Seal] **Seal Final Verification Result**

   - Do not hand-write the final \`.verify-result.json\`; Phase 1 and Phase 2 CLI calls already persisted it
   - Run:
     \`\`\`bash
     openspec verify seal "<change-name>" --json
     \`\`\`
   - The seal command validates the final top-level \`result\`, \`verificationContext\`, terminal \`optimization.status\`, and returns a deterministic seal hash
   - If verification fails, keep the persisted diagnostics so \`${verifyInvocation}\`, \`${continueInvocation}\`, and archive can consume the latest diagnostics`;
}

const VERIFY_HEURISTICS_AND_OUTPUT = `
**Verification Heuristics**:

- **Completeness**: focus on objective checklist items and explicit requirement coverage
- **Correctness**: require concrete evidence from final file contents before declaring PASS
- **Coherence**: look for meaningful contradictions, not cosmetic nitpicks
- **Optimization**: improve code only when behavior can be preserved under checkpoint protection
- **False positives**: when uncertain, prefer SUGGESTION over WARNING and WARNING over CRITICAL
- **Actionability**: every issue must include a concrete next action and file references when applicable

**Graceful Degradation**:

- If only \`tasks.md\` exists: verify task completion only and report skipped checks
- If tasks and specs exist: verify completeness and correctness, skip design checks
- If full artifacts exist: verify all three dimensions
- Always state which checks were skipped and why

**Output Format**:

Use clear markdown with:
- A table for the summary scorecard
- Grouped lists for CRITICAL, WARNING, and SUGGESTION issues
- Code references in \`file.ts:123\` format
- Specific, actionable recommendations
- No vague language like "consider reviewing"`;

function buildRereadVerifyInstructions(text: VerifyTemplateText): string {
  const verifyInvocation = `${text.commandPrefix ?? '/opsx:'}verify`;
  const continueInvocation = `${text.commandPrefix ?? '/opsx:'}continue`;

  return `${buildVerifyIntro(text, CLEAN_CONTEXT_VERIFY_PROTOCOL_REREAD)}

4. [Mode: Evidence] **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. [Mode: Evidence] **Verify Completeness**

   **Task Completion**:
   - If \`tasks.md\` exists in \`contextFiles\`, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add one CRITICAL issue per incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`openspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search for candidate implementation files
       - Read the final file contents for those candidates
       - Assess whether credible implementation evidence exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

5.5. [Mode: Evidence] **Git Evidence Investigation**

${GIT_EVIDENCE_PROTOCOL}

   Use git commands to guide the investigation:
   - Run \`git status\` to find modified, added, and deleted files
   - Run \`git diff\` to identify candidate implementation areas and suspicious omissions
   - Run \`git log -5 --oneline\` to understand recent context if needed

6. [Mode: Evidence] **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search for implementation evidence in code and tests
     - Read final file contents before assigning status
     - Record supporting and contradicting evidence with specific file paths and line ranges
     - If divergence is detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check whether the scenario conditions are handled in code
     - Check whether tests cover the scenario
     - If scenario coverage is incomplete or unclear:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

${CONFORMANCE_CHECK_RULES}

${OPSX_VERIFY_ALIGNMENT}

7. [Mode: Evidence] **Verify Coherence**

   **Design Adherence**:
   - If \`design.md\` exists in \`contextFiles\`:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction is detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no \`design.md\` exists: skip design adherence and state why

   **Code Pattern Consistency**:
   - Review new code for consistency with existing project patterns
   - Check naming, directory structure, and testing shape
   - If significant deviation is found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. [Mode: Evidence] **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status                |
   |--------------|-----------------------|
   | Completeness | X/Y tasks, N reqs     |
   | Correctness  | M/N reqs covered      |
   | Coherence    | Followed/Issues       |
   | Optimization | SKIPPED / IMPROVED... |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (must fix before archive)
   2. **WARNING** (should fix or consciously accept)
   3. **SUGGESTION** (non-blocking improvements)

   **Final Assessment**:
   - If CRITICAL issues exist: set result to \`FAIL_NEEDS_REMEDIATION\`
   - If no CRITICAL issues exist but warnings or suggestions remain: set result to \`PASS_WITH_WARNINGS\`
   - If all checks are clear: set result to \`PASS\`

   **Exit / Result Semantics**:
   - \`PASS\`: no CRITICAL, WARNING, or SUGGESTION follow-up is needed
   - \`PASS_WITH_WARNINGS\`: no CRITICAL issues, but warnings or suggestions remain
   - \`FAIL_NEEDS_REMEDIATION\`: one or more CRITICAL issues require write-back and rework

9. [Mode: Writeback] **Write Back CRITICAL Issues**

${VERIFY_WRITEBACK_RULES}

   - If no CRITICAL issues were found, leave \`tasks.md\` unchanged
   - If CRITICAL issues were found:
     - Unmark each affected completed task
     - Append or refresh the \`## Remediation\` section with typed fix items
     - Include the requirement name, issue summary, and owning task when possible

${buildCanonicalPhase1Step(10)}

${buildPhase2Step(11)}

${buildReverifyStep(
  12,
  `   - In \`${REREAD_VERIFY_EXECUTION_MODEL}\` mode, the current agent MUST re-read artifacts, git evidence, and final file contents again before assigning the speculative verdict\n`
)}

${buildPersistStep(13, verifyInvocation, continueInvocation)}

${VERIFY_HEURISTICS_AND_OUTPUT}`;
}

function buildSubagentVerifyInstructions(text: VerifyTemplateText): string {
  const verifyInvocation = `${text.commandPrefix ?? '/opsx:'}verify`;
  const continueInvocation = `${text.commandPrefix ?? '/opsx:'}continue`;

  return `${buildVerifyIntro(text, CLEAN_CONTEXT_VERIFY_PROTOCOL_SUBAGENT)}

4. [Mode: Evidence] **Assemble the Explicit Evidence Bundle**

   - Read every available artifact from \`contextFiles\`
   - Run \`git status\`, \`git diff\`, and \`git log -5 --oneline\`
   - Identify candidate implementation files from git evidence and requirement keywords
   - Read the final file contents for every candidate before handing control to a reviewer subagent
   - Read prior \`.verify-result.json\` if it exists
   - Normalize evidence file paths as relative POSIX paths for the reviewer payload
   - The top-level agent MAY gather evidence, but MUST NOT assign completeness, correctness, or coherence verdicts here

5. [Mode: Delegate Review] **Run the Reviewer Subagent for Canonical Phase 1**

   Delegate to a clean-context reviewer subagent with the explicit evidence bundle from Step 4.
   The coordinator MUST instruct the subagent to invoke the \`openspec-reviewer\` skill.

   The \`openspec-reviewer\` skill loads the full reviewer contract: role definition, hard constraints,
   input validation, 6-step verification protocol, severity thresholds and evidence standards,
   three-dimension coverage (completeness, correctness, coherence), OPSX alignment rules,
   structured JSON output schema with writeBackPlan semantics, and graceful degradation rules.

   Pass the explicit evidence bundle alongside the skill invoke as the subagent's input context:
   - \`changeArtifacts\`: proposal, specs, design, tasks, and OPSX delta when available
   - \`gitEvidence\`: \`git status\`, \`git diff\`, and \`git log -5 --oneline\`
   - \`finalFileContents\`: final contents for every candidate implementation file
   - \`priorVerifyResult\`: prior \`.verify-result.json\` when present
   - \`opsxContext\`: \`project.opsx.yaml\`, code map references, and relevant existing specs when available

   Wait for the complete reviewer payload before entering payload validation.
   The coordinator MUST NOT substitute its own completeness/correctness/coherence verdict.

${VERIFY_SUBAGENT_TIMEOUT_RULES}

${GIT_EVIDENCE_PROTOCOL}

${CONFORMANCE_CHECK_RULES}

${OPSX_VERIFY_ALIGNMENT}

6. [Mode: Validate Payload] **Validate the Reviewer Payload**

   - Fail closed if the reviewer payload is missing, malformed, or unsupported
   - Validate:
     - \`result\` is one of \`PASS\`, \`PASS_WITH_WARNINGS\`, or \`FAIL_NEEDS_REMEDIATION\`
     - every issue includes severity, concrete next action, and evidence citations
     - every evidence citation uses specific file paths and line ranges
     - every \`writeBackPlan\` entry targets \`tasks.md\` only and maps to a CRITICAL issue
   - If validation fails:
     - Stop verification
     - Report the payload defect explicitly
     - Do NOT silently downgrade to the reread skeleton

7. [Mode: Writeback] **Write Back CRITICAL Issues**

${VERIFY_WRITEBACK_RULES}

   - If the reviewer found no CRITICAL issues, leave \`tasks.md\` unchanged
   - If CRITICAL issues exist:
     - Apply the validated \`writeBackPlan\` to \`tasks.md\`
     - Unmark each affected completed task
     - Append or refresh the \`## Remediation\` section with typed fix items
     - Keep the top-level agent limited to deterministic file updates; judgment stays in the reviewer payload

${buildCanonicalPhase1Step(8)}

${buildPhase2Step(9)}

${buildReverifyStep(
  10,
  `   - In \`${SUBAGENT_VERIFY_EXECUTION_MODEL}\` mode, rebuild the explicit evidence bundle for the speculative worktree and invoke the reviewer subagent again for the speculative verdict\n   - The top-level agent MUST NOT substitute its own completeness / correctness / coherence judgment during \`P1_SPECULATIVE_FENCE\`\n`
)}

${buildPersistStep(11, verifyInvocation, continueInvocation)}

${VERIFY_HEURISTICS_AND_OUTPUT}`;
}

function buildVerifyInstructions(
  text: VerifyTemplateText,
  executionModel: VerifyExecutionModel
): string {
  if (executionModel === SUBAGENT_VERIFY_EXECUTION_MODEL) {
    return buildSubagentVerifyInstructions(text);
  }

  return buildRereadVerifyInstructions(text);
}

function createVerifySkillTemplate(executionModel: VerifyExecutionModel): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description:
      'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: buildVerifyInstructions(
      {
        input:
          'Optionally specify a change name and optionally request `--skip-optimization`. If omitted, you MUST prompt for available changes.',
      },
      executionModel
    ),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function createVerifyCommandTemplate(executionModel: VerifyExecutionModel): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: buildVerifyInstructions(
      {
        input:
          'Optionally specify a change name after `/opsx:verify` (e.g., `/opsx:verify add-auth`) and optionally pass `--skip-optimization`. If omitted, you MUST prompt for available changes.',
      },
      executionModel
    ),
  };
}

export function createVerifyChangeSkillTemplateForExecutionModel(
  executionModel: VerifyExecutionModel = REREAD_VERIFY_EXECUTION_MODEL
): SkillTemplate {
  return createVerifySkillTemplate(executionModel);
}

export function createOpsxVerifyCommandTemplateForExecutionModel(
  executionModel: VerifyExecutionModel = REREAD_VERIFY_EXECUTION_MODEL
): CommandTemplate {
  return createVerifyCommandTemplate(executionModel);
}

export function createVerifyChangeSkillTemplate(): SkillTemplate {
  return createVerifyChangeSkillTemplateForExecutionModel();
}

export function createOpsxVerifyCommandTemplate(): CommandTemplate {
  return createOpsxVerifyCommandTemplateForExecutionModel();
}

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return createVerifyChangeSkillTemplateForExecutionModel();
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return createOpsxVerifyCommandTemplateForExecutionModel();
}
